### ISSUE TITLE
Not an issue, Just a question

### ISSUE THREAD

**Issue by OgCheeseSauce69** [yatzu0001/BattleFN-Cracked-Fortnite-Cheat#1]
I assume this is axy0's friend? If so is it ok if i add you on discord, I can't get this thing working but i'm shit with PCs.

**Comment by yatzu0001** [comment]
> I assume this is axy0's friend? If so is it ok if i add you on discord, I can't get this thing working but i'm shit with PCs.

add me on discord

**Comment by OgCheeseSauce69** [comment]
Add Sitt#1019
